### ISSUE TITLE
Footer - Change "oversite" to "oversight".

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/platform-services-status#8]
This new site is great and hugely informative - well done!

I came across a trivial change - on the footer, I think you meant to use "oversight" rather than "oversite".  I looked through the repo but couldn't find the file where this code lives.

Good luck with this initiative!

**Comment by jleach** [comment]
Looks like someone got in and fixed it already. Footer reads :


Platform Services is a dedicated team providing high level administration and oversight
to the BC Gov's DevOps Platform.

**Comment by SteveChapmanBCDX** [comment]
Nice!  You guys are quick.
